spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hikinglog?createDatabaseIfNotExist=true
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000
server:
  port: 8080

# spring-security 암호키 설정
#jwt:
#  ecd5a5dc19762fea97d19fa4a3673438e17360f17140b0ce7bb9832dc3989916